### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by fgilsc** [marcellusnav/MyBusinessCentralHelpers#1]
Hey friend, I've just installed the extension and tried but it only showed a Blank Page...
![image](https://user-images.githubusercontent.com/15670597/54150072-e3f6c080-4437-11e9-8623-452ed0f8ad7a.png)

**Comment by marcellusnav** [comment]
Hi, Thanks for reporting the issue. I have assigned the application area property to the fields on the zoom line page and now it works. I also used Business Central Sandbox so it's no longer trying to use NAV 2018.
Let me know when you checked the latest :)
